name: cardeologist_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.14.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  window_manager: ^0.3.7
  reactive_forms: ^16.1.1
  reactive_date_time_picker: ^3.0.0
  freezed_annotation: ^2.4.1
  flutter_localizations:
    sdk: flutter
  intl: any
  get_it: ^7.6.4
  reactive_file_picker: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_close_app: ^1.0.0
  fullscreen_window: ^1.0.4
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.14.0
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
